### ISSUE TITLE
Benchmark graphique

### ISSUE THREAD

**Issue by lacaux-gerome** [PinkFlowerOfTheSunsetOfTheDeath/CMS#3]
Effectuer une veille. Dégager une liste des tendance graphique chez les CMS concurents (Wordpress, Bolt, Presstashop, Magento)

**Comment by pierre-robin** [comment]
https://docs.google.com/document/d/1rDO18F5_aDJ9nRLmak0M36KOHhPhb2a-ZpukAEczvS4/edit
