### ISSUE TITLE
Benchmark fonctionnel

### ISSUE THREAD

**Issue by lacaux-gerome** [PinkFlowerOfTheSunsetOfTheDeath/CMS#4]
Dégager des tendances technique et fonctionnel

**Comment by lacaux-gerome** [comment]
Connexion : 2 champs et 1 button submit
Création article et article : side bar -> listes status de l'article (publié / n publié , visibilité sur le site, heure de publication, wysiwyg
Backoffice global : side bar, nom du user.
Side bar : liens essentiels -> paramètres, articles, utlisateurs, pages
![image](https://user-images.githubusercontent.com/22907118/41231909-f42ae8bc-6d84-11e8-8ef3-d1a6855fb812.png)

**Comment by mariecharles** [comment]
DRUPAL = Principales fonctionnalités de l’interface:

Dashboard global
Gestion du contenu: arborescence du site
Gestion de l’arborescence du site (menus, blocs…)
Config
Rapports
Aide

Tips pour chaque feature avec des pop-up de demande de confirmation avant action.
Message de confirmation après action
Messages d’avertissement

Ajout de modules, plug-in  avec checklist 

Overview de tous les articles par vue avec tag, lien, plus d'options, tri des articles...
Pour ajout/modif d'article: tous les paramètres: visibilité, position
